# 
# Given two strings s and t which consist of only lowercase letters. 
# 
#  String t is generated by random shuffling string s and then add one more lett
# er at a random position. 
# 
#  Find the letter that was added in t. 
# 
#  Example:
#  
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
#  Related Topics 位运算 哈希表 
#  👍 153 👎 0


# leetcode submit region begin(Prohibit modification and deletion)
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return chr(sum(map(ord, t)) - sum(map(ord, s)))
        
# leetcode submit region end(Prohibit modification and deletion)
